
package com.imam.app;

import com.imam.dao.TarifFileDAO;
import com.imam.model.Paket;
import com.imam.model.Tarif;
import com.imam.model.Tipe;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author imam
 */
public class CourierApp extends javax.swing.JFrame {
    Paket paket;
    TarifFileDAO tfdao;
    Tipe tipe;
    
    //    Tarif [] tariffiledao;
    List<Tarif> kotaTujuan;
    Tarif [] kota; 
    
    public CourierApp() {
        initPaket();
        getKota();
        tfdao = new TarifFileDAO();
        paket = new Paket();
        kotaTujuan = TarifFileDAO.pilihKota();
        initComponents();
    }
    
    public void initPaket () {
        try {
            kotaTujuan = TarifFileDAO.pilihKota();
        } catch (Exception e) {
        }
       
    }
    
    public Tarif[] getKota () {
        int size = kotaTujuan.size();
        kota = new Tarif[size];
        for (int i = 0; i < size; i++) {
            Tarif tarif = kotaTujuan.get(i);
            kota[i] = tarif;
        }
        return kota;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serviceButtonGroup = new javax.swing.ButtonGroup();
        asuransiButtonGrup = new javax.swing.ButtonGroup();
        pembayaranButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jenisLayananLabel = new javax.swing.JLabel();
        asuransiLa = new javax.swing.JLabel();
        totalBiayaLabel = new javax.swing.JLabel();
        totalBiayaTextLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jenisLayanan = new javax.swing.JLabel();
        asuransi = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        noResiLabel = new javax.swing.JLabel();
        noResiTextField = new javax.swing.JTextField();
        pembayaranLabel = new javax.swing.JLabel();
        cashRadio = new javax.swing.JRadioButton();
        kreditRadio = new javax.swing.JRadioButton();
        debitRadio = new javax.swing.JRadioButton();
        pembayaranTextField = new javax.swing.JTextField();
        tglSkrgLabel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        detailPaketPanel = new javax.swing.JPanel();
        tujuanLabel = new javax.swing.JLabel();
        kotaTujuanCombo = new javax.swing.JComboBox<>(kota);
        tipeLabel = new javax.swing.JLabel();
        tipePaketCombo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        lebarPaketTextField = new javax.swing.JTextField();
        panjangPaketTextField = new javax.swing.JTextField();
        tinggiPaketTextField = new javax.swing.JTextField();
        lebarLabel = new javax.swing.JLabel();
        panjangLabel = new javax.swing.JLabel();
        tinggiLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        beratPaketTextField = new javax.swing.JTextField();
        beratPaketLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        regulerRadio = new javax.swing.JRadioButton();
        onsRadio = new javax.swing.JRadioButton();
        sdsRadio = new javax.swing.JRadioButton();
        hdsRadio = new javax.swing.JRadioButton();
        ekonomiRadio = new javax.swing.JRadioButton();
        asuransiLabel = new javax.swing.JLabel();
        asuransiPaketYARadio = new javax.swing.JRadioButton();
        asuransiPaketTIDAKRadio = new javax.swing.JRadioButton();
        hitungButton = new javax.swing.JButton();
        hargaPaketLabel = new javax.swing.JLabel();
        hargaPaketTextField = new javax.swing.JTextField();
        tipePaketTextField = new javax.swing.JTextField();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namaPengirimTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamatPengirimTextArea = new javax.swing.JTextArea();
        kodePosLabel = new javax.swing.JLabel();
        provinsiPengirimLabel = new javax.swing.JLabel();
        kodePosPengirimTextField = new javax.swing.JTextField();
        provinsPengirimTextField = new javax.swing.JTextField();
        noTelpPengirimLabel = new javax.swing.JLabel();
        noTelpPengirimTextField = new javax.swing.JTextField();
        kotaPengirimLabel = new javax.swing.JLabel();
        kotaPengirimTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        namaPenerimaTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatPenerimaTextArea = new javax.swing.JTextArea();
        provinsiPenerimaLabel = new javax.swing.JLabel();
        provinsiPenerimaTextField = new javax.swing.JTextField();
        kodePosPenerimaLabel = new javax.swing.JLabel();
        kodePosPenerimaTextField = new javax.swing.JTextField();
        noTelpPenerimaLabel = new javax.swing.JLabel();
        noTelpPenerimaTextField = new javax.swing.JTextField();
        kotaPenerimaTextField = new javax.swing.JTextField();
        kotaPenerimaLabel = new javax.swing.JLabel();
        checkoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Courier Application");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Transaksi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel2.setText("Berat Paket");

        jLabel3.setText("Kota Tujuan");

        jenisLayananLabel.setText("Jenis Layanan");

        asuransiLa.setText("Asuransi");

        totalBiayaLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        totalBiayaLabel.setText("Total Biaya");
        totalBiayaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                none(evt);
            }
        });

        totalBiayaTextLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        totalBiayaTextLabel.setText("-");

        jLabel11.setText("-");

        jLabel12.setText("-");

        jenisLayanan.setText("-");

        asuransi.setText("-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jenisLayananLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jenisLayanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalBiayaLabel)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(asuransiLa))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalBiayaTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(asuransi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisLayananLabel)
                    .addComponent(jenisLayanan))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asuransiLa)
                    .addComponent(asuransi))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalBiayaLabel)
                    .addComponent(totalBiayaTextLabel))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/add_icon.png"))); // NOI18N
        addButton.setText("Add New");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        noResiLabel.setText("No. Resi");

        pembayaranLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pembayaranLabel.setText("Pembayaran");

        pembayaranButtonGroup.add(cashRadio);
        cashRadio.setText("Cash");

        pembayaranButtonGroup.add(kreditRadio);
        kreditRadio.setText("Credit");
        kreditRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kreditRadioActionPerformed(evt);
            }
        });

        pembayaranButtonGroup.add(debitRadio);
        debitRadio.setText("Debit");
        debitRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debitRadioActionPerformed(evt);
            }
        });

        pembayaranTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaranTextFieldActionPerformed(evt);
            }
        });

        tglSkrgLabel.setText("                     ");
        tglSkrgLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tglSkrgLabelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        detailPaketPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detail Paket", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tujuanLabel.setText("Tujuan");

        kotaTujuanCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kotaTujuanComboActionPerformed(evt);
            }
        });

        tipeLabel.setText("Tipe");

        tipePaketCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Document", "Electronic", "Food", "Lainnya" }));
        tipePaketCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipePaketComboActionPerformed(evt);
            }
        });

        jLabel9.setText("Dimensi");

        lebarPaketTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lebarPaketTextFieldActionPerformed(evt);
            }
        });

        panjangPaketTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panjangPaketTextFieldActionPerformed(evt);
            }
        });

        tinggiPaketTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggiPaketTextFieldActionPerformed(evt);
            }
        });

        lebarLabel.setText("L");

        panjangLabel.setText("P");

        tinggiLabel.setText("T");

        jLabel13.setText("X");

        jLabel14.setText("X");

        jLabel15.setText("cm");

        beratPaketLabel.setText("Berat");

        jLabel17.setText("Service ");

        serviceButtonGroup.add(regulerRadio);
        regulerRadio.setText("Reguler");
        regulerRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regulerRadioActionPerformed(evt);
            }
        });

        serviceButtonGroup.add(onsRadio);
        onsRadio.setText("ONS");
        onsRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onsRadioActionPerformed(evt);
            }
        });

        serviceButtonGroup.add(sdsRadio);
        sdsRadio.setText("SDS");
        sdsRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdsRadioActionPerformed(evt);
            }
        });

        serviceButtonGroup.add(hdsRadio);
        hdsRadio.setText("HDS");
        hdsRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hdsRadioActionPerformed(evt);
            }
        });

        serviceButtonGroup.add(ekonomiRadio);
        ekonomiRadio.setText("Ekonomi");
        ekonomiRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekonomiRadioActionPerformed(evt);
            }
        });

        asuransiLabel.setText("Asuransi");

        asuransiButtonGrup.add(asuransiPaketYARadio);
        asuransiPaketYARadio.setText("Ya");
        asuransiPaketYARadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asuransiPaketYARadioActionPerformed(evt);
            }
        });

        asuransiButtonGrup.add(asuransiPaketTIDAKRadio);
        asuransiPaketTIDAKRadio.setText("Tidak");
        asuransiPaketTIDAKRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asuransiPaketTIDAKRadioActionPerformed(evt);
            }
        });

        hitungButton.setText("Hitung");
        hitungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungButtonActionPerformed(evt);
            }
        });

        hargaPaketLabel.setText("Harga");

        javax.swing.GroupLayout detailPaketPanelLayout = new javax.swing.GroupLayout(detailPaketPanel);
        detailPaketPanel.setLayout(detailPaketPanelLayout);
        detailPaketPanelLayout.setHorizontalGroup(
            detailPaketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPaketPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailPaketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailPaketPanelLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addGroup(detailPaketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regulerRadio)
                            .addComponent(onsRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sdsRadio))
                        .addGap(56, 56, 56)
                        .addGroup(detailPaketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hdsRadio)
                            .addComponent(ekonomiRadio)))
                    .addGroup(detailPaketPanelLayout.createSequentialGroup()
                        .addComponent(asuransiLabel)
                        .addGap(18, 18, 18)
                        .addComponent(asuransiPaketYARadio)
                        .addGap(26, 26, 26)
                        .addComponent(asuransiPaketTIDAKRadio))
                    .addGroup(detailPaketPanelLayout.createSequentialGroup()
                        .addGroup(detailPaketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detailPaketPanelLayout.createSequentialGroup()
                                .addGroup(detailPaketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(detailPaketPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lebarPaketTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13))
                                    .addGroup(detailPaketPanelLayout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(lebarLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(detailPaketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panjangLabel)
                                    .addComponent(panjangPaketTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(detailPaketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tinggiLabel)
                                    .addGroup(detailPaketPanelLayout.createSequentialGroup()
                                        .addComponent(tinggiPaketTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel15))))
                            .addGroup(detailPaketPanelLayout.createSequentialGroup()
                                .addComponent(hargaPaketLabel)
                                .addGap(26, 26, 26)
                                .addComponent(hargaPaketTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hitungButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detailPaketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, detailPaketPanelLayout.createSequentialGroup()
                            .addComponent(beratPaketLabel)
                            .addGap(18, 18, 18)
                            .addComponent(beratPaketTextField))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, detailPaketPanelLayout.createSequentialGroup()
                            .addGroup(detailPaketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tujuanLabel)
                                .addComponent(tipeLabel))
                            .addGap(13, 13, 13)
                            .addGroup(detailPaketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tipePaketTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tipePaketCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kotaTujuanCombo, 0, 285, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        detailPaketPanelLayout.setVerticalGroup(
            detailPaketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailPaketPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailPaketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lebarLabel)
                    .addComponent(panjangLabel)
                    .addComponent(tinggiLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailPaketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lebarPaketTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tinggiPaketTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panjangPaketTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailPaketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beratPaketLabel)
                    .addComponent(beratPaketTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(detailPaketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipeLabel)
                    .addComponent(tipePaketCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tipePaketTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(detailPaketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tujuanLabel)
                    .addComponent(kotaTujuanCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailPaketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(detailPaketPanelLayout.createSequentialGroup()
                        .addGroup(detailPaketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(regulerRadio)
                            .addComponent(ekonomiRadio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailPaketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(onsRadio)
                            .addComponent(hdsRadio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sdsRadio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailPaketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asuransiLabel)
                    .addComponent(asuransiPaketYARadio)
                    .addComponent(asuransiPaketTIDAKRadio))
                .addGap(33, 33, 33)
                .addGroup(detailPaketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargaPaketLabel)
                    .addComponent(hargaPaketTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hitungButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(detailPaketPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 53, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(detailPaketPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 103, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Detail Paket", jPanel4);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pengirim", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel4.setText("Nama");

        jLabel5.setText("Alamat");

        namaPengirimTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPengirimTextFieldActionPerformed(evt);
            }
        });

        alamatPengirimTextArea.setColumns(20);
        alamatPengirimTextArea.setRows(5);
        jScrollPane2.setViewportView(alamatPengirimTextArea);

        kodePosLabel.setText("Kode pos");

        provinsiPengirimLabel.setText("Provinsi");

        noTelpPengirimLabel.setText("Nomor Telepon");

        kotaPengirimLabel.setText("Kota");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaPengirimTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(kodePosPengirimTextField)
                    .addComponent(provinsPengirimTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(noTelpPengirimTextField)
                    .addComponent(kotaPengirimTextField)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(kodePosLabel)
                            .addComponent(provinsiPengirimLabel)
                            .addComponent(noTelpPengirimLabel)
                            .addComponent(kotaPengirimLabel)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaPengirimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kotaPengirimLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kotaPengirimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(provinsiPengirimLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(provinsPengirimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kodePosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kodePosPengirimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(noTelpPengirimLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noTelpPengirimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Penerima", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel6.setText("Nama");

        namaPenerimaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPenerimaTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Alamat");

        alamatPenerimaTextArea.setColumns(20);
        alamatPenerimaTextArea.setRows(5);
        jScrollPane1.setViewportView(alamatPenerimaTextArea);

        provinsiPenerimaLabel.setText("Provinsi");

        kodePosPenerimaLabel.setText("Kode pos");

        noTelpPenerimaLabel.setText("Nomor Telepon");

        kotaPenerimaLabel.setText("Kota");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaPenerimaTextField)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(provinsiPenerimaTextField)
                    .addComponent(kodePosPenerimaTextField)
                    .addComponent(noTelpPenerimaTextField)
                    .addComponent(kotaPenerimaTextField)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(provinsiPenerimaLabel)
                            .addComponent(kodePosPenerimaLabel)
                            .addComponent(noTelpPenerimaLabel)
                            .addComponent(kotaPenerimaLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaPenerimaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kotaPenerimaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kotaPenerimaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(provinsiPenerimaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(provinsiPenerimaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kodePosPenerimaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kodePosPenerimaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(noTelpPenerimaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noTelpPenerimaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jPanel2);

        jTabbedPane1.addTab("Data Profile", jSplitPane1);

        checkoutButton.setText("Checkout");
        checkoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pembayaranLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cashRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(debitRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kreditRadio)
                .addGap(18, 18, 18)
                .addComponent(pembayaranTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkoutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(printButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(noResiLabel)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tglSkrgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noResiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tglSkrgLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(noResiLabel)
                            .addComponent(noResiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(printButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveButton)
                                .addGap(42, 42, 42)
                                .addComponent(cancelButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pembayaranLabel)
                    .addComponent(cashRadio)
                    .addComponent(kreditRadio)
                    .addComponent(debitRadio)
                    .addComponent(pembayaranTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkoutButton))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaPenerimaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPenerimaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPenerimaTextFieldActionPerformed

    private void namaPengirimTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPengirimTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPengirimTextFieldActionPerformed

    private void lebarPaketTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lebarPaketTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lebarPaketTextFieldActionPerformed

    private void panjangPaketTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panjangPaketTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panjangPaketTextFieldActionPerformed

    private void tinggiPaketTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggiPaketTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggiPaketTextFieldActionPerformed

    private void tipePaketComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipePaketComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipePaketComboActionPerformed

    private void regulerRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regulerRadioActionPerformed
        // TODO add your handling code here:
        if (regulerRadio.isSelected()) {
            ekonomiRadio.setSelected(false);
            onsRadio.setSelected(false);
            sdsRadio.setSelected(false);
            hdsRadio.setSelected(false);
//            Layer3ButtonNext.setEnabled(true);
//            pengiriman.setHargaPaket(pengiriman.getTipeReg());
        }
    }//GEN-LAST:event_regulerRadioActionPerformed

    private void onsRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onsRadioActionPerformed
        // TODO add your handling code here:
        double berat = Double.parseDouble(beratPaketTextField.getText().trim());
      paket.setBerat((int) berat);
        if(onsRadio.isSelected()){
         //totalHarga = paket.hitungTotalREGNonAsuransi(indexKota);
      }
    }//GEN-LAST:event_onsRadioActionPerformed

    private void sdsRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdsRadioActionPerformed
        // TODO add your handling code here:
        double berat = Double.parseDouble(beratPaketTextField.getText().trim());
      paket.setBerat((int) berat);
        if(sdsRadio.isSelected()){
         //totalHarga = paket.hitungTotalREGNonAsuransi(indexKota);
      }
    }//GEN-LAST:event_sdsRadioActionPerformed

    private void hdsRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hdsRadioActionPerformed
        // TODO add your handling code here:
        double berat = Double.parseDouble(beratPaketTextField.getText().trim());
      paket.setBerat((int) berat);
        if(hdsRadio.isSelected()){
         //totalHarga = paket.hitungTotalREGNonAsuransi(indexKota);
      }
    }//GEN-LAST:event_hdsRadioActionPerformed

    private void ekonomiRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekonomiRadioActionPerformed
        // TODO add your handling code here:
        double berat = Double.parseDouble(beratPaketTextField.getText().trim());
      paket.setBerat((int) berat);
        if(ekonomiRadio.isSelected()){
         //totalHarga = paket.hitungTotalREGNonAsuransi(indexKota);
      }
    }//GEN-LAST:event_ekonomiRadioActionPerformed

    private void asuransiPaketYARadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asuransiPaketYARadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asuransiPaketYARadioActionPerformed

    private void asuransiPaketTIDAKRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asuransiPaketTIDAKRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asuransiPaketTIDAKRadioActionPerformed

    private void hitungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungButtonActionPerformed
        // TODO add your handling code here:
        
//        DecimalFormat df = new DecimalFormat("###,###.##"); 
//        String reguler = df.format(tipe.getReg());
//        regulerRadio.getSelected();
//        String ekonomi = df.format(tipe.getEkonomi());
//        ekonomiRadio.getSelectedItem();
//        String sds = df.format(tipe.getSds());
//        ekonomiRadio.getSelectedItem();
//        String ons = df.format(tipe.getOns());
//        ekonomiRadio.getSelectedItem();
//        String hds = df.format(tipe.getHds());
//        ekonomiRadio.getSelectedItem();
////        
        Paket paket = new Paket();
//        paket.setBerat(Integer.parseInt(beratPaketTextField.getText().trim()));
          //tarif.setJasaLayanan().getHds(Double.parseDouble(regulerRadio.getActionCommand()));
//        
////        paket.setPaketTarif(hargaPaketTextField.getText()); 
//        //paket.setKotaTujuan((kotaTujuanCombo.getSelectedItem().trim())); 
//        String kotaTujuan = (String.valueOf(kotaTujuanCombo));
//        String namaPaket = (String.valueOf(tipePaketCombo));
//        
//        System.out.println("Berat : " + paket.getBerat());
//        
//        if (kotaTujuan.equalsIgnoreCase(String.valueOf(kotaTujuanCombo.getSelectedItem()))) {
//            double total = paket.hitungBiaya(String.valueOf(kotaTujuanCombo.getSelectedItem()), 
//                    String.valueOf(kotaTujuanCombo.getSelectedItem()));
//            totalBiayaTextLabel.setText(total+" Ribu");
//        }
        for (Tarif tarif : kotaTujuan) {
            if(tarif.getKotaTujuan().equalsIgnoreCase(kotaTujuanCombo.getSelectedItem().toString())){
                paket.setBerat(Integer.parseInt(beratPaketTextField.getText()));
                double biaya = paket.hitungBiaya(kotaTujuanCombo.getSelectedItem().toString(), "reguler");
                System.out.println("Biaya: " + biaya);
            }
        }
    }//GEN-LAST:event_hitungButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        paket = new Paket();
    }//GEN-LAST:event_addButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
//        report.set
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printButtonActionPerformed

    private void kreditRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kreditRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kreditRadioActionPerformed

    private void debitRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debitRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_debitRadioActionPerformed

    private void tglSkrgLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tglSkrgLabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tglSkrgLabelAncestorAdded

    private void none(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none

    private void pembayaranTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaranTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pembayaranTextFieldActionPerformed

    private void kotaTujuanComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kotaTujuanComboActionPerformed
        // TODO add your handling code here:
        Tarif tarif = (Tarif)kotaTujuanCombo.getSelectedItem();
    }//GEN-LAST:event_kotaTujuanComboActionPerformed

    private void checkoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourierApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourierApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourierApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourierApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourierApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextArea alamatPenerimaTextArea;
    private javax.swing.JTextArea alamatPengirimTextArea;
    private javax.swing.JLabel asuransi;
    private javax.swing.ButtonGroup asuransiButtonGrup;
    private javax.swing.JLabel asuransiLa;
    private javax.swing.JLabel asuransiLabel;
    private javax.swing.JRadioButton asuransiPaketTIDAKRadio;
    private javax.swing.JRadioButton asuransiPaketYARadio;
    private javax.swing.JLabel beratPaketLabel;
    private javax.swing.JTextField beratPaketTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton cashRadio;
    private javax.swing.JButton checkoutButton;
    private javax.swing.JRadioButton debitRadio;
    private javax.swing.JPanel detailPaketPanel;
    private javax.swing.JRadioButton ekonomiRadio;
    private javax.swing.JLabel hargaPaketLabel;
    private javax.swing.JTextField hargaPaketTextField;
    private javax.swing.JRadioButton hdsRadio;
    private javax.swing.JButton hitungButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jenisLayanan;
    private javax.swing.JLabel jenisLayananLabel;
    private javax.swing.JLabel kodePosLabel;
    private javax.swing.JLabel kodePosPenerimaLabel;
    private javax.swing.JTextField kodePosPenerimaTextField;
    private javax.swing.JTextField kodePosPengirimTextField;
    private javax.swing.JLabel kotaPenerimaLabel;
    private javax.swing.JTextField kotaPenerimaTextField;
    private javax.swing.JLabel kotaPengirimLabel;
    private javax.swing.JTextField kotaPengirimTextField;
    private javax.swing.JComboBox<Tarif> kotaTujuanCombo;
    private javax.swing.JRadioButton kreditRadio;
    private javax.swing.JLabel lebarLabel;
    private javax.swing.JTextField lebarPaketTextField;
    private javax.swing.JTextField namaPenerimaTextField;
    private javax.swing.JTextField namaPengirimTextField;
    private javax.swing.JLabel noResiLabel;
    private javax.swing.JTextField noResiTextField;
    private javax.swing.JLabel noTelpPenerimaLabel;
    private javax.swing.JTextField noTelpPenerimaTextField;
    private javax.swing.JLabel noTelpPengirimLabel;
    private javax.swing.JTextField noTelpPengirimTextField;
    private javax.swing.JRadioButton onsRadio;
    private javax.swing.JLabel panjangLabel;
    private javax.swing.JTextField panjangPaketTextField;
    private javax.swing.ButtonGroup pembayaranButtonGroup;
    private javax.swing.JLabel pembayaranLabel;
    private javax.swing.JTextField pembayaranTextField;
    private javax.swing.JButton printButton;
    private javax.swing.JTextField provinsPengirimTextField;
    private javax.swing.JLabel provinsiPenerimaLabel;
    private javax.swing.JTextField provinsiPenerimaTextField;
    private javax.swing.JLabel provinsiPengirimLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JRadioButton regulerRadio;
    private javax.swing.JButton saveButton;
    private javax.swing.JRadioButton sdsRadio;
    private javax.swing.ButtonGroup serviceButtonGroup;
    private javax.swing.JLabel tglSkrgLabel;
    private javax.swing.JLabel tinggiLabel;
    private javax.swing.JTextField tinggiPaketTextField;
    private javax.swing.JLabel tipeLabel;
    private javax.swing.JComboBox<String> tipePaketCombo;
    private javax.swing.JTextField tipePaketTextField;
    private javax.swing.JLabel totalBiayaLabel;
    private javax.swing.JLabel totalBiayaTextLabel;
    private javax.swing.JLabel tujuanLabel;
    // End of variables declaration//GEN-END:variables
}
